services:
  naryo:
    image: naryo/naryo:latest
    restart: on-failure
    ports:
      - "8060:8060"
    networks:
      - naryo
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      KAFKA_ADDRESSES: kafka:9092
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: naryo
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: naryo
      POSTGRESQL_USERNAME: naryo
      POSTGRESQL_PASSWORD: naryo
      RABBIT_HOST: rabbitmq
      RABBIT_USER: naryo
      RABBIT_PASSWORD: naryo
      RABBIT_PORT: 5672
      RABBIT_EXCHANGE: naryo
    profiles:
      - naryo

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data/db:/data/db
    networks:
      - naryo
    profiles:
      - mongodb

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    profiles:
      - kafka
    networks:
      - naryo

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "8080:15672"
    networks:
      - naryo
    environment:
      RABBITMQ_DEFAULT_USER: naryo
      RABBITMQ_DEFAULT_PASS: naryo
    profiles:
      - rabbitmq

  postgresql:
    image: postgres:14
    container_name: postgres_container
    ports:
      - "5432:5432"
    networks:
      - naryo
    environment:
      POSTGRES_PASSWORD: naryo
      POSTGRES_USER: naryo
      POSTGRES_DB: naryo
    volumes:
      - $HOME/postgres/data/db:/var/lib/postgresql/data
    profiles:
      - postgresql

networks:
  naryo:
    driver: bridge
