naryo:
    nodes:
        - id: 061d75e5-2016-4e98-bdfa-d6cd32b28529
          name: test-naryo-23d6d942-226b-4b8a-9a1c-d323cd342223
          type: ETHEREUM
          connection:
              type: HTTP
              endpoint:
                url: http://localhost:8545
    broadcasting:
        configuration:
            - id: 59cf5501-d801-4e2a-b557-dbf245809edd
              type: HTTP
              endpoint:
                url: http://localhost:8080
        broadcasters:
            - id: 59cf5501-d801-4e2a-b557-dbf245809edd
              configurationId: 59cf5501-d801-4e2a-b557-dbf245809edd
              target:
                type: ALL
                destination: /events
    filters:
        - id: fa1abf87-fc96-44a1-ae20-c4aecb3d5909
          name: my-transfer-filter
          type: EVENT
          nodeId: 061d75e5-2016-4e98-bdfa-d6cd32b28529
          scope: GLOBAL
          specification:
              signature: Transfer(address indexed, address indexed, uint256)
              specification:
                signature: Transfer(address indexed, address indexed, uint256)
          sync:
            type: BLOCK_BASED
            initialBlock: 0

    event-stores:
      - nodeId: 061d75e5-2016-4e98-bdfa-d6cd32b28529
        type: SERVER
        strategy: BLOCK_BASED
        targets:
          - type: BLOCK
            destination: /blocks
          - type: TRANSACTION
            destination: /transactions
          - type: CONTRACT_EVENT
            destination: /contract-events
        serverType: HTTP
        endpoint:
          url: "http://localhost:5002/"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: naryo
      authentication-database: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/naryo_database
    username: admin
    password: mellon
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#logging:
#  level:
#    root: DEBUG

