name: Librevents CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew assemble --parallel --scan

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ github.sha }}

  core:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run core tests with coverage
        run: ./gradlew core:test --parallel --scan

      - name: Upload Core JaCoCo HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: core-jacoco-html-reports
          path: core/build/reports/jacoco-html/

  privacy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run privacy tests with coverage
        run: ./gradlew privacy:test --parallel --scan

      - name: Upload Privacy JaCoCo HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: privacy-jacoco-html-reports
          path: privacy/build/reports/jacoco-html/

  server:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run integration tests with coverage
        run: ./gradlew server:test --scan

      - name: Upload Server JaCoCo HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: server-jacoco-html-reports
          path: server/build/reports/jacoco-html/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: build/libs
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run integration tests with coverage
        run: ./gradlew integration-tests:test --scan

      - name: Upload Server JaCoCo HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: server-jacoco-html-reports
          path: server/build/reports/jacoco-html/
